
blueprint:
  name: "ZHA - IKEA TRADFRI - 2 Button Remote - Time Lights FIXED"
  description: "ON/OFF day/night light by time. FIXED logic."
  domain: automation
  input:
    remote:
      name: IKEA remote
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
    light:
      name: Day light
      selector:
        entity:
          domain: light
    night_light:
      name: Night light
      selector:
        entity:
          domain: light
    speed:
      name: Dim speed
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          unit_of_measurement: ms
      default: 500
    night_start:
      name: Night from
      selector:
        time:
      default: "20:00:00"
    night_end:
      name: Night to
      selector:
        time:
      default: "06:00:00"

mode: restart

variables:
  var_speed: !input speed
  transition: "{{ (var_speed / 1000) | float }}"

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - choose:
      # ON - short press
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - condition: template
            value_template: >
              {% set ns = states('input_datetime.night_start') | as_datetime %}
              {% set ne = states('input_datetime.night_end') | as_datetime %}
              {% set nowh = now().hour %}
              {% set nowm = now().minute %}
              {% set nsh = ns.hour %}
              {% set nsm = ns.minute %}
              {% set neh = ne.hour %}
              {% set nem = ne.minute %}
              {% set now_min = nowh * 60 + nowm %}
              {% set ns_min = nsh * 60 + nsm %}
              {% set ne_min = neh * 60 + nem %}
              {{ (ns_min > ne_min and (now_min >= ns_min or now_min <= ne_min)) or (ns_min <= ne_min and now_min >= ns_min and now_min <= ne_min) }}
          sequence:
            - service: light.turn_on
              target:
                entity_id: !input night_light
              data:
                transition: "{{ transition }}"
          default:
            - service: light.turn_on
              target:
                entity_id: !input light
              data:
                transition: "{{ transition }}"

      # MOVE WITH ON/OFF - hold ON for brightness up
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              sequence:
                - condition: template
                  value_template: >
                    {% set ns = states('input_datetime.night_start') | as_datetime %}
                    {% set ne = states('input_datetime.night_end') | as_datetime %}
                    {% set nowh = now().hour %}
                    {% set nowm = now().minute %}
                    {% set nsh = ns.hour %}
                    {% set nsm = ns.minute %}
                    {% set neh = ne.hour %}
                    {% set nem = ne.minute %}
                    {% set now_min = nowh * 60 + nowm %}
                    {% set ns_min = nsh * 60 + nsm %}
                    {% set ne_min = neh * 60 + nem %}
                    {{ (ns_min > ne_min and (now_min >= ns_min or now_min <= ne_min)) or (ns_min <= ne_min and now_min >= ns_min and now_min <= ne_min) }}
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: !input night_light
                      data:
                        brightness_step_pct: 10
                        transition: "{{ transition }}"
                  default:
                    - service: light.turn_on
                      target:
                        entity_id: !input light
                      data:
                        brightness_step_pct: 10
                        transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed

      # OFF - short press
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - condition: template
            value_template: >
              {% set ns = states('input_datetime.night_start') | as_datetime %}
              {% set ne = states('input_datetime.night_end') | as_datetime %}
              {% set nowh = now().hour %}
              {% set nowm = now().minute %}
              {% set nsh = ns.hour %}
              {% set nsm = ns.minute %}
              {% set neh = ne.hour %}
              {% set nem = ne.minute %}
              {% set now_min = nowh * 60 + nowm %}
              {% set ns_min = nsh * 60 + nsm %}
              {% set ne_min = neh * 60 + nem %}
              {{ (ns_min > ne_min and (now_min >= ns_min or now_min <= ne_min)) or (ns_min <= ne_min and now_min >= ns_min and now_min <= ne_min) }}
            sequence:
              - service: light.turn_off
                target:
                  entity_id: !input night_light
                data:
                  transition: "{{ transition }}"
            default:
              - service: light.turn_off
                target:
                  entity_id: !input light
                data:
                  transition: "{{ transition }}"

      # MOVE - hold OFF for brightness down
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - repeat:
              sequence:
                - condition: template
                  value_template: >
                    {% set ns = states('input_datetime.night_start') | as_datetime %}
                    {% set ne = states('input_datetime.night_end') | as_datetime %}
                    {% set nowh = now().hour %}
                    {% set nowm = now().minute %}
                    {% set nsh = ns.hour %}
                    {% set nsm = ns.minute %}
                    {% set neh = ne.hour %}
                    {% set nem = ne.minute %}
                    {% set now_min = nowh * 60 + nowm %}
                    {% set ns_min = nsh * 60 + nsm %}
                    {% set ne_min = neh * 60 + nem %}
                    {{ (ns_min > ne_min and (now_min >= ns_min or now_min <= ne_min)) or (ns_min <= ne_min and now_min >= ns_min and now_min <= ne_min) }}
                  sequence:
                    - service: light.turn_on
                      target:
                        entity_id: !input night_light
                      data:
                        brightness_step_pct: -10
                        transition: "{{ transition }}"
                  default:
                    - service: light.turn_on
                      target:
                        entity_id: !input light
                      data:
                        brightness_step_pct: -10
                        transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed
    default: []
