
blueprint:
  name: "ZHA - IKEA TRADFRI - 2 Button Remote - Time Based Lights"
  description: "ON/OFF controls day/night light based on time. Works with groups."
  source_url: https://github.com/metbril/home-assistant-blueprints/blob/main/automation/zha_ikea_tradfri_2button_onoff_brightness.yaml
  domain: automation
  input:
    remote:
      name: IKEA TRADFRI remote
      description: Select button.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
    light:
      name: Day light/group
      description: Light for daytime.
      selector:
        entity:
          domain: light
    night_light:
      name: Night light
      description: Light for nighttime.
      selector:
        entity:
          domain: light
    speed:
      name: Dim speed
      description: Dimming speed (ms).
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          unit_of_measurement: ms
          mode: slider
      default: 500
    night_start:
      name: Night starts
      description: e.g. 22:00
      selector:
        time:
      default: "22:00:00"
    night_end:
      name: Night ends
      description: e.g. 06:00
      selector:
        time:
      default: "06:00:00"

mode: restart
max_exceeded: silent

variables:
  var_speed: !input speed
  transition_speed: "{{ (var_speed / 1000) | float(0) }}"

trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote

action:
- choose:
  - conditions:
      - "{{ trigger.event.data.command == 'on' }}"
    sequence:
    - choose:
      - conditions: >
          {{
            (now().hour * 3600 + now().minute * 60 + now().second) >= (states('input_datetime.night_start') | int(0)) or
            (now().hour * 3600 + now().minute * 60 + now().second) <= (states('input_datetime.night_end') | int(0))
          }}
        sequence:
        - service: light.turn_on
          target:
            entity_id: !input night_light
          data:
            transition: "{{ transition_speed }}"
      default:
      - service: light.turn_on
        target:
          entity_id: !input light
        data:
          transition: "{{ transition_speed }}"

  - conditions:
      - "{{ trigger.event.data.command == 'move_with_on_off' }}"
    sequence:
    - repeat:
        while: []
        sequence:
        - choose:
          - conditions: >
              {{
                (now().hour * 3600 + now().minute * 60 + now().second) >= (states('input_datetime.night_start') | int(0)) or
                (now().hour * 3600 + now().minute * 60 + now().second) <= (states('input_datetime.night_end') | int(0))
              }}
            sequence:
            - service: light.turn_on
              target:
                entity_id: !input night_light
              data:
                brightness_step_pct: 10
                transition: "{{ transition_speed }}"
          default:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_step_pct: 10
              transition: "{{ transition_speed }}"
        - delay:
            milliseconds: !input speed

  - conditions:
      - "{{ trigger.event.data.command == 'off' }}"
    sequence:
    - choose:
      - conditions: >
          {{
            (now().hour * 3600 + now().minute * 60 + now().second) >= (states('input_datetime.night_start') | int(0)) or
            (now().hour * 3600 + now().minute * 60 + now().second) <= (states('input_datetime.night_end') | int(0))
          }}
        sequence:
        - service: light.turn_off
          target:
            entity_id: !input night_light
          data:
            transition: "{{ transition_speed }}"
      default:
      - service: light.turn_off
        target:
          entity_id: !input light
        data:
          transition: "{{ transition_speed }}"

  - conditions:
      - "{{ trigger.event.data.command == 'move' }}"
    sequence:
    - repeat:
        while: []
        sequence:
        - choose:
          - conditions: >
              {{
                (now().hour * 3600 + now().minute * 60 + now().second) >= (states('input_datetime.night_start') | int(0)) or
                (now().hour * 3600 + now().minute * 60 + now().second) <= (states('input_datetime.night_end') | int(0))
              }}
            sequence:
            - service: light.turn_on
              target:
                entity_id: !input night_light
              data:
                brightness_step_pct: -10
                transition: "{{ transition_speed }}"
          default:
          - service: light.turn_on
            target:
              entity_id: !input light
            data:
              brightness_step_pct: -10
              transition: "{{ transition_speed }}"
        - delay:
            milliseconds: !input speed

  default: []
