
blueprint:
  name: "ZHA - IKEA TRADFRI - 2 Button Remote - On/Off and Brightness (časový režim)"
  description: "Stejný blueprint jako původní, ale ON/OFF ovládá denní/noční světlo podle času."
  source_url: https://github.com/metbril/home-assistant-blueprints/blob/main/automation/zha_ikea_tradfri_2button_onoff_brightness.yaml
  domain: automation
  input:
    remote:
      name: IKEA TRADFRI remote control
      description: Vyber tlačítko k použití.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
          multiple: false
    light:
      name: Denní světlo / skupina
      description: Světlo pro denní režim (nebo light group).
      selector:
        entity:
          domain: light
          multiple: false
    night_light:
      name: Noční světlo
      description: Světlo pro noční režim (např. slabší lampička).
      selector:
        entity:
          domain: light
          multiple: false
    speed:
      name: Rychlost
      description: Rychlost změny jasu při dlouhém držení (ms).
      selector:
        number:
          min: 100.0
          max: 1000.0
          step: 100.0
          unit_of_measurement: milliseconds
          mode: slider
      default: 500
    night_start:
      name: Začátek nočního režimu
      description: Čas od kdy použít noční světlo (např. 22:00).
      selector:
        time:
      default: "22:00:00"
    night_end:
      name: Konec nočního režimu
      description: Čas do kdy použít noční světlo (např. 06:00).
      selector:
        time:
      default: "06:00:00"

mode: restart
max_exceeded: silent

variables:
  var_speed: !input speed
  transition_speed: "{{ (var_speed / 1000) | float(0) }}"
  v_night_start: !input night_start
  v_night_end: !input night_end
  current_light: >
    {% set now_time = now().strftime('%H:%M:%S') %}
    {% set start = v_night_start %}
    {% set end = v_night_end %}
    {% if start > end %}
      {% if now_time >= start or now_time <= end %}
        {{ night_light }}
      {% else %}
        {{ light }}
      {% endif %}
    {% else %}
      {% if now_time >= start and now_time <= end %}
        {{ night_light }}
      {% else %}
        {{ light }}
      {% endif %}
    {% endif %}

trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote

action:
- choose:
  - conditions: '{{ trigger.event.data.command == "on" }}'
    sequence:
    - service: light.turn_on
      target:
        entity_id: "{{ current_light }}"
      data:
        transition: "{{ transition_speed }}"

  - conditions: '{{ trigger.event.data.command == "move_with_on_off" }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ current_light }}"
          data:
            brightness_step_pct: 10
            transition: "{{ transition_speed }}"
        - delay:
            milliseconds: !input speed

  - conditions: '{{ trigger.event.data.command == "off" }}'
    sequence:
    - service: light.turn_off
      target:
        entity_id: "{{ current_light }}"
      data:
        transition: "{{ transition_speed }}"

  - conditions: '{{ trigger.event.data.command == "move" }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ current_light }}"
          data:
            brightness_step_pct: -10
            transition: "{{ transition_speed }}"
        - delay:
            milliseconds: !input speed

  default: []
