
blueprint:
  name: "ZHA - IKEA TRADFRI - 2 Button Remote - On/Off and Brightness (časový režim)"
  description: "ON/OFF ovládá denní/noční světlo podle času. Funguje i dlouhý stisk."
  source_url: https://github.com/metbril/home-assistant-blueprints/blob/main/automation/zha_ikea_tradfri_2button_onoff_brightness.yaml
  domain: automation
  input:
    remote:
      name: IKEA TRADFRI remote
      description: Vyber tlačítko.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
          multiple: false
    light:
      name: Denní světlo / skupina
      description: Světlo pro den (např. light group).
      selector:
        entity:
          domain: light
          multiple: false
    night_light:
      name: Noční světlo
      description: Světlo pro noc.
      selector:
        entity:
          domain: light
          multiple: false
    speed:
      name: Rychlost dimování
      description: Rychlost změny jasu při držení (ms).
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          unit_of_measurement: ms
          mode: slider
      default: 500
    night_start:
      name: Noční režim od
      description: Např. 22:00.
      selector:
        time:
      default: "22:00:00"
    night_end:
      name: Noční režim do
      description: Např. 06:00 (funguje přes půlnoc).
      selector:
        time:
      default: "06:00:00"

mode: restart
max_exceeded: silent

variables:
  var_speed: !input speed
  transition_speed: "{{ (var_speed / 1000) | float(0) }}"
  night_start_time: "{{ states('input_datetime.night_start') | as_timestamp(default=0) }}"
  night_end_time: "{{ states('input_datetime.night_end') | as_timestamp(default=0) }}"
  now_time: "{{ now().timestamp() }}"
  current_light: >
    {% if night_start_time > night_end_time %}
      {{ night_light if (now_time >= night_start_time or now_time <= night_end_time) else light }}
    {% else %}
      {{ night_light if (now_time >= night_start_time and now_time <= night_end_time) else light }}
    {% endif %}

trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote

action:
- choose:
  - conditions: "{{ trigger.event.data.command == 'on' }}"
    sequence:
    - service: light.turn_on
      target:
        entity_id: "{{ current_light }}"
      data:
        transition: "{{ transition_speed }}"

  - conditions: "{{ trigger.event.data.command == 'move_with_on_off' }}"
    sequence:
    - repeat:
        while: []
        sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ current_light }}"
          data:
            brightness_step_pct: 10
            transition: "{{ transition_speed }}"
        - delay:
            milliseconds: !input speed

  - conditions: "{{ trigger.event.data.command == 'off' }}"
    sequence:
    - service: light.turn_off
      target:
        entity_id: "{{ current_light }}"
      data:
        transition: "{{ transition_speed }}"

  - conditions: "{{ trigger.event.data.command == 'move' }}"
    sequence:
    - repeat:
        while: []
        sequence:
        - service: light.turn_on
          target:
            entity_id: "{{ current_light }}"
          data:
            brightness_step_pct: -10
            transition: "{{ transition_speed }}"
        - delay:
            milliseconds: !input speed

  default: []
