
blueprint:
  name: "IKEA TRADFRI Time Lights - UNIVERSAL ZHA"
  description: "Vyber JAKOJKOLI ZHA device - funguje s tvým IKEA switch!"
  domain: automation
  input:
    remote:
      name: ZHA Device (IKEA switch)
      description: Vyber své IKEA tlačítko (objeví se mezi ZHA zařízeními).
      selector:
        device:
          integration: zha
          multiple: false
    day_light:
      name: Denní světlo (group)
      selector:
        entity:
          domain: light
    night_light:
      name: Noční světlo
      selector:
        entity:
          domain: light
    speed:
      name: Dim speed (ms)
      default: 500
      selector:
        number:
          min: 100
          max: 1000
          step: 100
          mode: slider
    night_start:
      name: Noční režim OD
      selector:
        time:
      default: "20:00:00"
    night_end:
      name: Noční režim DO
      selector:
        time:
      default: "06:00:00"

mode: restart

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      transition: "{{ (!input speed / 1000) | float }}"
      now_h = "{{ now().hour }}"
      now_m = "{{ now().minute }}"
      now_minutes: "{{ now_h | int * 60 + now_m | int }}"
      start_h = "{{ states('input_datetime.night_start') | timestamp_custom('%H') | int }}"
      start_m = "{{ states('input_datetime.night_start') | timestamp_custom('%M') | int }}"
      end_h = "{{ states('input_datetime.night_end') | timestamp_custom('%H') | int }}"
      end_m = "{{ states('input_datetime.night_end') | timestamp_custom('%M') | int }}"
      start_minutes: "{{ start_h * 60 + start_m }}"
      end_minutes: "{{ end_h * 60 + end_m }}"
      is_night: >
        {% if start_minutes > end_minutes %}
          {{ now_minutes >= start_minutes or now_minutes <= end_minutes }}
        {% else %}
          {{ now_minutes >= start_minutes and now_minutes <= end_minutes }}
        {% endif %}

  - choose:
      - conditions: "{{ trigger.event.data.command == 'on' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{ night_light if is_night else day_light }}"
            data:
              transition: "{{ transition }}"
      - conditions: "{{ trigger.event.data.command == 'off' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ night_light if is_night else day_light }}"
            data:
              transition: "{{ transition }}"
      - conditions: "{{ trigger.event.data.command == 'move_with_on_off' }}"
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ night_light if is_night else day_light }}"
                  data:
                    brightness_step_pct: 10
                    transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed
      - conditions: "{{ trigger.event.data.command == 'move' }}"
        sequence:
          - repeat:
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ night_light if is_night else day_light }}"
                  data:
                    brightness_step_pct: -10
                    transition: "{{ transition }}"
                - delay:
                    milliseconds: !input speed
